language: julia
notifications:
  email: false
julia:
  - 1.0
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1.0
      script: julia --project=docs -e '
        using Pkg;
        Pkg.develop(PackageSpec(; path=pwd()));
        Pkg.instantiate();
        include("docs/make.jl");'
      after_success: skip
