name = "SimpleMock"
uuid = "a896ed2c-15a5-4479-b61d-a0e88e2a1d25"
authors = ["Chris de Graaf <chrisadegraaf@gmail.com>"]
version = "0.3.1"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"

[compat]
julia = "1"

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Suppressor", "Test"]
